### PR TITLE
Updated normalize.scss  Filipino translation

### PR DESCRIPTION
**Pull request by agentzero1**
I translated the strings into Filipino

### CODE REVIEW

**Comment by agentzero1** [comment]
Hi I’m still waiting for the approval for this project. I’m hoping for a positive response. Thank you!

**Comment by agentzero1** [comment]
Hi, are you no longer merging Filipino translations? Is there a problem with this PR? Please advise so that I can fix asap. Thank you.

**Comment by lfaraone** [comment]
Hi @agentzero1 ! Thanks for the PR.

It looks like you translated comments in a SCSS file — it doesn't make sense to translate code comments, generally. We also aren't working on translating todogroup.org at this time.

**Comment by agentzero1** [comment]
What file should I translate sir ?

**Pull request closed without merging**
